name: Stackblitz templates


run-name: Playwright stackblitz templates 🚀
on:
 workflow_dispatch:
 schedule:
   - cron: "59 23 * * *"
jobs:
 run-stackblitz-templates-tests:
   runs-on: macos-14
   steps:
     - name: Check out code
       uses: actions/checkout@v4


     - name: Install Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 20


     - run: corepack enable
     - run: pnpm --version
     - uses: actions/setup-node@v4
       with:
         node-version: 20
         cache: "pnpm"
         cache-dependency-path: "**/pnpm-lock.yaml"
     - name: install
       run: pnpm install --no-frozen-lockfile --prefer-offline


     - name: Install dependencies with Playwright
       run: |
         pnpm playwright install --with-deps


     - name: Run tests
       run: |
        cd apps/e2e-tests
        npx playwright test -c examples.config.ts checkStackblitzTemplates.spec.ts
 on-failure:
    runs-on: macos-14
    if: always()
    steps:
      - uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          notification_title: " ${{github.event.workflow_run.name}} - ${{github.event.workflow_run.conclusion}} on ${{github.event.workflow_run.head_branch}} - <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"
          message_format: ":fire: *${{github.event.workflow_run.name}}* ${{github.event.workflow_run.conclusion}} in <${{github.server_url}}/${{github.repository}}/${{github.event.workflow_run.head_branch}}|${{github.repository}}>"
          footer: "Linked Repo <${{github.server_url}}/${{github.repository}}|${{github.repository}}> | <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FAIL_SLACK_URL }}